[versions]
kafkaConnect="7.6.0-ccs"
javaxWsRsApi = "2.1.1"
jerseyCommon = "2.39.1"
assertj = "3.24.2"
junit = "5.10.1"
mockito = "5.7.0"

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
